export type NavItem = {
  label: string;
  href: string;
  /** Hidden until the module that owns the page ships. */
  enabled: boolean;
  /** Shown in the header only from the `sm` breakpoint up (still in ⌘K). Keeps 360 px headers from overflowing. */
  desktopOnly?: boolean;
};

export const siteConfig = {
  name: "Jitin Gupta",
  role: "Applied AI Architect",
  description:
    "Applied AI Architect: agentic AI systems and quantitative forecasting.",
  url: "https://jitin-site.vercel.app",
  email: "jitin4389@gmail.com",
  linkedin: "https://www.linkedin.com/in/jitin-gupta-20395421/",
  /** Generated by `npm run cv:pdf` from src/content/profile.ts. */
  cvPdf: "/jitin-gupta-cv.pdf",
  /** Header + ⌘K links. The site name in the header always links home. */
  nav: [
    { label: "About", href: "/#about", enabled: true, desktopOnly: true },
    {
      label: "Experience",
      href: "/#experience",
      enabled: true,
      desktopOnly: true,
    },
    { label: "Work", href: "/work", enabled: true },
    { label: "CV", href: "/cv", enabled: true },
    { label: "Contact", href: "/#contact", enabled: true },
    { label: "Writing", href: "/writing", enabled: true, desktopOnly: true },
  ] satisfies NavItem[],
  /** Indexable pages, for the sitemap. Section anchors are not pages. */
  routes: ["/", "/cv", "/work", "/writing"],
};

export function getEnabledNav(items: NavItem[] = siteConfig.nav): NavItem[] {
  return items.filter((item) => item.enabled);
}
